import type { Metadata } from "next";
import "./globals.css";
import { Lily_Script_One } from "next/font/google";
import Footer from "@/components/footer/Footer";
import Navbar from "@/components/navigation/Navbar";
import Providers from "@/components/Providers"; // Import the new Providers component

const lilyScript = Lily_Script_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-lily",
});

export const metadata: Metadata = {
  title: "Hotel Management App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lilyScript.variable}>
        <Providers>
          <Navbar />
          {children}
          <div className="bottom-0">
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
