import type { Metadata } from "next";
import "./globals.css";
import { Lily_Script_One } from "next/font/google";
import Providers from "@/components/Providers";
import LayoutWrapper from "@/components/navigation/LayoutWrapper"; // ✅ Client-side wrapper for path checks

const lilyScript = Lily_Script_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-lily",
});

export const metadata: Metadata = {
  title: "Hotel Management App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={lilyScript.variable}>
        <Providers>
          <LayoutWrapper>{children}</LayoutWrapper>{" "}
          {/* ✅ Handles dynamic rendering */}
        </Providers>
      </body>
    </html>
  );
}
